const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

// ── Network metadata lookup ──
const NETWORK_META = {
  ganache:  { name: "Ganache",  chainId: 1337 },
  localhost: { name: "Localhost", chainId: 31337 },
  sepolia:  { name: "Sepolia",  chainId: 11155111 },
};

async function main() {
  const networkName = hre.network.name;
  const isLocal = ["ganache", "localhost", "hardhat"].includes(networkName);
  const meta = NETWORK_META[networkName] || { name: networkName, chainId: 0 };

  console.log(`🚀 Deploying CertificateVerification to ${meta.name} (${networkName})...\n`);

  const [deployer] = await hre.ethers.getSigners();
  console.log("📋 Deployer address:", deployer.address);
  console.log(
    "💰 Deployer balance:",
    hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)),
    "ETH\n"
  );

  // ── Deploy ──
  const CertificateVerification = await hre.ethers.getContractFactory("CertificateVerification");
  const contract = await CertificateVerification.deploy();
  await contract.waitForDeployment();

  const contractAddress = await contract.getAddress();
  console.log("✅ CertificateVerification deployed to:", contractAddress);
  console.log("👑 Admin address:", deployer.address);

  // ── Wait for block confirmations (skip on local chains — they mine instantly) ──
  if (!isLocal) {
    console.log("\n⏳ Waiting for 5 block confirmations...");
    const deployTx = contract.deploymentTransaction();
    if (deployTx) {
      await deployTx.wait(5);
    }
    console.log("✅ 5 confirmations received.\n");

    // ── Etherscan verification note ──
    console.log("🔍 To verify on Etherscan, run:");
    console.log(`   npx hardhat verify --network ${networkName} ${contractAddress}\n`);
  } else {
    console.log("\n⚡ Local chain detected — skipping block confirmations.\n");
  }

  // ── Bridge to Frontend: write ABI + address to dapp/src/contract.js ──
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "CertificateVerification.sol",
    "CertificateVerification.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const frontendDir = path.join(__dirname, "..", "dapp", "src");
  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  const contractFileContent = `// Auto-generated by deploy.js — do not edit manually
// Network: ${meta.name} (Chain ID ${meta.chainId})
export const CONTRACT_ADDRESS = "${contractAddress}";

export const ADMIN_ADDRESS = "${deployer.address}";

export const NETWORK_NAME = "${meta.name}";

export const CHAIN_ID = ${meta.chainId};

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  const contractFilePath = path.join(frontendDir, "contract.js");
  fs.writeFileSync(contractFilePath, contractFileContent);
  console.log("📄 ABI + Address written to dapp/src/contract.js");
  console.log(`🎉 Deployment to ${meta.name} complete!\n`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
